[project]
name = "ai"
version = "0.1.0"
description = ""
authors = [
    {name = "github-actions[bot]",email = "nevernevernever69@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[tool.poetry.dependencies]

